### ISSUE TITLE
Doesn't work with jquery-3.1.1

### ISSUE THREAD

**Issue by pip8786** [timpler/jquery.initialize#6]
I was not able to get this to work as is with jquery 3.1.1. I tracked the issue down to line 51:
`msobservers.initialize(this.selector, callback);`
In that call, this.selector is null. It seems selector has been deprecated: https://api.jquery.com/selector/ 

When I reworked the code to just pass selector and callback everything started working.

**Comment by dbezborodovrp** [comment]
Well, that's a pain in the ass.

**Comment by timpler** [comment]
umm... @dbezborodovrp I agree. Any ideas how to handle it when `selector` is not available?

**Comment by dbezborodovrp** [comment]
That sounds like a good solution. I think we should keep the old interface though for backward-compatibility.

**Comment by timpler** [comment]
I'm not able to make proper update right now. PR would be very welcome :)

**Comment by Whetu-Paitai** [comment]
Hey there bud, looking to try your plugin, but had to go back to jquery 2.x for it to work. Just wondering if this plugin will eventually be updated? If so, I will keep an eye out here.

**Comment by mhulse** [comment]
Just made a PR, see #7. Thanks!

**Comment by timpler** [comment]
#7 is merged now. Thanks a lot @mhulse

**Comment by mhulse** [comment]
Sure thing! Want me to bump that version and update readme in a new PR?

**Comment by timpler** [comment]
would be nice ;)

**Comment by timpler** [comment]
Thanks for help! Merged.
